version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cgreen-db"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vhz8b2r0rt07"
s3_prefix = "cgreen-db"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
